scorecard:
  version: v1alpha2
  output: text
  bundle: deploy/olm-catalog/service-telemetry-operator/metadata
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/infra.watch_v1alpha1_servicetelemetry_cr.yaml"
        csv-path: "deploy/olm-catalog/service-telemetry-operator/1.0.0-beta1/service-telemetry-operator.v1.0.0-beta1.clusterserviceversion.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/infra.watch_v1alpha1_servicetelemetry_cr.yaml"
        csv-path: "deploy/olm-catalog/service-telemetry-operator/1.0.0-beta1/service-telemetry-operator.v1.0.0-beta1.clusterserviceversion.yaml"
