scorecard:
  output: text
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/infra.watch_v1alpha1_servicetelemetry_cr.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/infra.watch_v1alpha1_servicetelemetry_cr.yaml"
        csv-path: "deploy/olm-catalog/service-telemetry-operator/0.1.1/service-telemetry-operator.v0.1.1.clusterserviceversion.yaml"
