---
- job:
    name: stf-base
    # defined in: https://review.rdoproject.org/cgit/config/tree/zuul.d/_jobs-crc.yaml
    parent: base-simple-crc
    abstract: true
    description: |
      Run the stf-run-ci role, and then test stf
    roles:  # adds in dependent roles i.e. put it in the role path
      - zuul: github.com/openstack-k8s-operators/ci-framework
    # These are the additional repos that zuul will clone
    required-projects:
      - name: openstack-k8s-operators/ci-framework
        override-checkout: main
    pre-run:
      - ci/prepare.yml
    run:
      - ci/deploy_stf.yml
      - ci/test_stf.yml
    post-run:
      - ci/post-collect_logs.yml
    nodeset: centos-9-crc-xxl
    # The default (~30 minutes) is not enough to run through all the job stages
    timeout: 3600
    vars:
      # Pass vars to crc cli https://review.rdoproject.org/cgit/config/tree/playbooks/crc/simple-start.yaml#n30
      crc_parameters: '--memory 16000 --disk-size 80 --cpus 6'  # Increase from 14336

- job:
    name: stf-crc-latest-nightly_bundles
    parent: stf-base
    description:
      Deploy STF nightly bundles
    vars:
      scenario: "nightly_bundles"
    
- job:
    name: stf-crc-latest-local_build
    parent: stf-base
    description: |
      Build images locally and deploy STF
    vars:
      scenario: "local_build"

- job:
    name: stf-multi-crc-base
    abstract: true
    description: |
      Temperory base job for crc jobs; the crc jobs will eventually use stf-base as a job, once PR
    parent: stf-base
    run:
      - ci/check_ocp_version.yml
    post-run:
      - ci/post-collect_logs.yml

- job:
    name: stf-crc-ocp410
    parent: stf-multi-crc-base
    vars:
      crc_ocp_bundle: 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.10.22/crc_libvirt_4.10.22_amd64.crcbundle'
      ocp_version: '4.10.22'

- job:
    name: stf-crc-ocp411
    parent: stf-multi-crc-base
    vars:
      crc_ocp_bundle: 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.11.18/crc_libvirt_4.11.18_amd64.crcbundle'
      ocp_version: '4.11.18'

- job:
    name: stf-crc-ocp412
    parent: stf-multi-crc-base
    vars:
      crc_ocp_bundle: 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.12.13/crc_libvirt_4.12.13_amd64.crcbundle'
      ocp_version: '4.12.13'

- job:
    name: stf-crc-ocp413
    parent: stf-multi-crc-base
    vars:
      crc_ocp_bundle: 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.13.14/crc_libvirt_4.13.14_amd64.crcbundle'
      ocp_version: '4.13.14'

- project:
    name: infrawatch/service-telemetry-operator
    github-check:
      jobs:
        #- stf-crc-latest-nightly_bundles
        #- stf-crc-latest-local_build
        - stf-crc-ocp411
        - stf-crc-ocp412
        - stf-crc-ocp413

