---
- job:
    name: stf-base
    # defined in: https://review.rdoproject.org/cgit/config/tree/zuul.d/_jobs-crc.yaml
    parent: base-simple-crc
    abstract: true
    description: |
      Run the stf-run-ci role, and then test stf
    roles:  # adds in dependent roles i.e. put it in the role path
      - zuul: github.com/openstack-k8s-operators/ci-framework
    # These are the additional repos that zuul will clone
    required-projects:
      - name: openstack-k8s-operators/ci-framework
        override-checkout: main
      - name: github.com/infrawatch/service-telemetry-operator
      - name: github.com/infrawatch/smart-gateway-operator
      - name: github.com/infrawatch/sg-bridge
      - name: github.com/infrawatch/sg-core
      - name: github.com/infrawatch/prometheus-webhook-snmp
    pre-run:
      - ci/prepare.yml
    run:
      - ci/deploy_stf.yml
      - ci/test_stf.yml
    post-run:
      - ci/post-collect_logs.yml
    nodeset: centos-9-crc-xxl
    # The default (~30 minutes) is not enough to run through all the job stages
    timeout: 3600
    vars:
      # Pass vars to crc cli https://review.rdoproject.org/cgit/config/tree/playbooks/crc/simple-start.yaml#n30
      crc_parameters: '--memory 16000 --disk-size 80 --cpus 6'  # Increase from 14336

- job:
    name: stf-crc-nightly_bundles
    parent: stf-base
    abstract: true
    description: |
      Deploy STF using the nightly bundles
    vars:
      scenario: "nightly_bundles"

- job:
    name: stf-crc-local_build
    parent: stf-base
    abstract: true
    description: |
      Build images locally and deploy STF
    vars:
      scenario: "local_build"

- job:
    name: stf-crc-local_build-index_deploy
    parent: stf-base
    abstract: true
    description: |
      Build STF locally and deploy from index
    vars:
      scenario: "local_build-index_deploy"

- job:
    name: stf-crc-ocp_412-nightly_bundles
    parent: stf-crc-nightly_bundles
    description: |
      Deploy STF using the nightly bundles on OCP 4.12
    vars:
      crc_ocp_bundle: 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.12.13/crc_libvirt_4.12.13_amd64.crcbundle'

- job:
    name: stf-crc-ocp_413-nightly_bundles
    parent: stf-crc-nightly_bundles
    description: |
      Deploy STF using the nightly bundles on OCP 4.13
    vars:
      crc_ocp_bundle: 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.13.14/crc_libvirt_4.13.14_amd64.crcbundle'

- job:
    name: stf-crc-ocp_412-local_build
    parent: stf-crc-local_build
    description: |
      Build images locally and deploy STF on OCP 4.12
    vars:
      crc_ocp_bundle: 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.12.13/crc_libvirt_4.12.13_amd64.crcbundle'

- job:
    name: stf-crc-ocp_413-local_build
    parent: stf-crc-local_build
    description: |
      Build images locally and deploy STF on OCP 4.13
    vars:
      crc_ocp_bundle: 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.13.14/crc_libvirt_4.13.14_amd64.crcbundle'

- job:
    name: stf-crc-ocp_412-local_build-index_deploy
    parent: stf-crc-local_build-index_deploy
    description: |
      Build STF locally and deploy from index on OCP 4.12
    vars:
      crc_ocp_bundle: 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.12.13/crc_libvirt_4.12.13_amd64.crcbundle'

- job:
    name: stf-crc-ocp_413-local_build-index_deploy
    parent: stf-crc-local_build-index_deploy
    description: |
      Build STF locally and deploy from index on OCP 4.13
    vars:
      crc_ocp_bundle: 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/4.13.14/crc_libvirt_4.13.14_amd64.crcbundle'

- project-template:
    name: stf-crc-jobs
    description: |
      STF CRC jobs that build and deploy STF
    github-check:
      jobs:
        - stf-crc-ocp_412-nightly_bundles:
            voting: false
        - stf-crc-ocp_412-local_build
        - stf-crc-ocp_412-local_build-index_deploy
        - stf-crc-ocp_413-nightly_bundles:
            voting: false
        - stf-crc-ocp_413-local_build
        - stf-crc-ocp_413-local_build-index_deploy

- project:
    name: infrawatch/service-telemetry-operator
    templates:
      - stf-crc-jobs
