---
- job:
    name: stf-base
    # defined in: https://review.rdoproject.org/cgit/config/tree/zuul.d/_jobs-crc.yaml
    parent: base-simple-crc
    # need to set cluster-monitoring
    abstract: true
    description: |
      Run the stf-run-ci role, and then test stf
    # irrelevant-files
    roles:  # adds in dependent roles i.e. put it in the role path
      - zuul: github.com/openstack-k8s-operators/ci-framework
    # These are the additional repos that zuul will clone
    required-projects:
      - name: openstack-k8s-operators/ci-framework
        override-checkout: main
    # requires:  # defines a resource that needs to be available e.g. a content-provide job will provide a resource
    # dependencies:  # list a job that needs to run successfully for this one
    pre-run:
      - ci/prepare.yml
    run:
      - ci/deploy_stf.yml
      - ci/test_stf.yml
    post-run:
      - ci/post-collect_logs.yml
    nodeset: centos-9-crc-xxl
    # The default (~30 minutes) is not enough to run through all the job stages
    timeout: 3600
    vars:
      # Pass vars to crc cli https://review.rdoproject.org/cgit/config/tree/playbooks/crc/simple-start.yaml#n30
        # memory is set to  14336 when monitoring is enabled, default is 14000
        # need to increase that. try a lot more to begin with
      crc_parameters: '--memory 16000 --disk-size 80 --cpus 6'  # Increase from 14336
      # need a base job here, for now to request the specific versions of OCP

      # content provider job that provides stf-15.
      # MIGHT need OCP

      # all jobs would depend on a combo of the stf and ocp content providers

#stf-1.5-ocp-4.10
#  parent: stf-base
#  dependencies: [make-ocp-4.10]
#  requires:
#    - "ocp-4.10"
#
#stf-1.5-ocp-4.12
#  parent: stf-base
#stf-1.5-ocp-pre-release
#  parent: stf-base

- job:
    name: stf-crc-latest-local_build
    parent: stf-base
    description: |
      Build images locally and deploy STF
    vars:
      scenario: "local_build"

- project:
    name: infrawatch/service-telemetry-operator
    github-check:
      jobs:
        - stf-crc-latest-local_build
