---
- nodeset:
    name: stf-crc_extracted-ocp416
    nodes:
      - name: controller
        label: cloud-centos-9-stream-tripleo-vexxhost
      - name: crc
        label: coreos-crc-extracted-2-39-0-3xl

- nodeset:
    name: stf-crc_extracted-ocp418
    nodes:
      - name: controller
        label: cloud-centos-9-stream-tripleo-vexxhost
      - name: crc
        label: coreos-crc-extracted-2-48-0-3xl

- job:
    name: stf-base-2node
    parent: podified-multinode-edpm-deployment-crc
    description: |
      A base job for STF that deploys extracted CRC with a 2-node topology.
      This job is based on the cookbook example in: https://github.com/openstack-k8s-operators/ci-framework/blob/main/docs/source/cookbooks/zuul-job-nodeset.md
      All non-abstract jobs that inherit from this must have a nodeset configured.
    abstract: true
    required-projects:
      - name: github.com/openstack-k8s-operators/dataplane-operator
        override-checkout: main
      - name: github.com/openstack-k8s-operators/infra-operator
        override-checkout: main
      - name: github.com/openstack-k8s-operators/openstack-operator
        override-checkout: main
      - name: github.com/openstack-k8s-operators/openstack-must-gather
        override-checkout: main
    #pre-run:
    #  - ci/pre-2node.yml
    vars:
      cifmw_deploy_edpm: false
      podified_validation: true
      cifmw_run_tests: false
    extra-vars:
      crc_ci_bootstrap_networking:
        networks:
          default:
            range: 192.168.122.0/24
            mtu: 1500
          internal-api:
            vlan: 20
            range: 172.17.0.0/24
          storage:
            vlan: 21
            range: 172.18.0.0/24
          tenant:
            vlan: 22
            range: 172.19.0.0/24
        instances:
          controller:
            networks:
              default:
                ip: 192.168.122.11
          crc:
            networks:
              default:
                ip: 192.168.122.10
              internal-api:
                ip: 172.17.0.5
              storage:
                ip: 172.18.0.5
              tenant:
                ip: 172.19.0.5

- job:
    name: stf-crc-deployment
    parent: stf-base-2node
    description: |
      A provider job that provisions CRC.
    abstract: false
    pre-run:
      - ci/pre-2node.yml
    run:
      - ci/prepare.yml
      - ci/pause-the-job.yml

- job:
    name: stf-base
    parent: stf-base-2node
    abstract: true
    description: |
      Run the stf-run-ci role, and then test stf
      Any non-abstract jobs that inherit from this must pass a `scenario` var.
    roles:  # adds in dependent roles i.e. put it in the role path
      - zuul: github.com/openstack-k8s-operators/ci-framework
    # These are the additional repos that zuul will clone
    required-projects:
      - name: openstack-k8s-operators/ci-framework
        override-checkout: main
      - name: github.com/infrawatch/service-telemetry-operator
      - name: github.com/infrawatch/smart-gateway-operator
      - name: github.com/infrawatch/sg-bridge
      - name: github.com/infrawatch/sg-core
      - name: github.com/infrawatch/prometheus-webhook-snmp
    #pre-run:
    #  - ci/prepare.yml
    run:
      - ci/deploy_stf.yml
      - ci/test_stf.yml
    post-run:
      - ci/post-collect_logs.yml
    # The default (~30 minutes) is not enough to run through all the job stages
    timeout: 3600

- job:
    name: stf-crc-local_build
    parent: stf-base
    abstract: true
    description: |
      Build images locally and deploy STF
    vars:
      scenario: "local_build"

- job:
    name: stf-crc-local_build-index_deploy
    parent: stf-base
    abstract: true
    description: |
      Build STF locally and deploy from index
    vars:
      scenario: "local_build-index_deploy"

- job:
    name: stf-crc-ocp_416-local_build
    parent: stf-crc-local_build
    description: |
      Build STF locally and deploy from index on OCP 4.16
    nodeset: stf-crc_extracted-ocp416

- job:
    name: stf-crc-ocp_418-local_build
    parent: stf-crc-local_build
    description: |
      Build STF locally and deploy from index on OCP 4.18
    nodeset: stf-crc_extracted-ocp418

- job:
    name: stf-crc-ocp_416-local_build-index_deploy
    parent: stf-crc-local_build-index_deploy
    description: |
      Build STF locally and deploy from index on OCP 4.16
    nodeset: stf-crc_extracted-ocp416

- job:
    name: stf-crc-ocp_418-local_build-index_deploy
    parent: stf-crc-local_build-index_deploy
    description: |
      Build STF locally and deploy from index on OCP 4.18
    nodeset: stf-crc_extracted-ocp418

- project-template:
    name: stf-crc-jobs
    description: |
      STF CRC jobs that build and deploy STF
    github-check:
      debug: true
      jobs:
        - stf-crc-deployment
        - stf-crc-ocp_416-local_build:
            dependencies: 
              -stf-crc-deployment
        - stf-crc-ocp_418-local_build
        - stf-crc-ocp_416-local_build-index_deploy
        - stf-crc-ocp_418-local_build-index_deploy

- project:
    name: infrawatch/service-telemetry-operator
    # templates:
    #   - stf-crc-jobs
    github-check:
      jobs:
        - stf-crc-deployment
        - stf-crc-ocp_416-local_build:
            dependencies:
              - stf-crc-deployment
  
