apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-telemetry-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: service-telemetry-operator
  template:
    metadata:
      labels:
        name: service-telemetry-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: service-telemetry-operator
      containers:
        - name: operator
          image: <<OPERATOR_IMAGE_PULLSPEC>>
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          env:
            - name: ANSIBLE_LOCAL_TEMP
              value: /tmp/ansible-local
            - name: ANSIBLE_REMOTE_TEMP
              value: /tmp/ansible-local
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "service-telemetry-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: RELATED_IMAGE_PROMETHEUS_WEBHOOK_SNMP_IMAGE
              value: <<RELATED_IMAGE_PROMETHEUS_WEBHOOK_SNMP_PULLSPEC>>
            - name: RELATED_IMAGE_OAUTH_PROXY_IMAGE
              value: <<RELATED_IMAGE_OAUTH_PROXY_PULLSPEC>>
            - name: RELATED_IMAGE_PROMETHEUS_IMAGE
              value: <<RELATED_IMAGE_PROMETHEUS_PULLSPEC>>
            - name: RELATED_IMAGE_ALERTMANAGER_IMAGE
              value: <<RELATED_IMAGE_ALERTMANAGER_PULLSPEC>>
      volumes:
        - name: tmp
          emptyDir: {}
