- name: Create configmap for OAUTH CA certs
  k8s:
    definition:
      api_version: v1
      kind: ConfigMap
      metadata:
        name: serving-certs-ca-bundle
        namespace: '{{ ansible_operator_meta.namespace }}'
        annotations:
          service.beta.openshift.io/inject-cabundle: 'true'

- name: Check for existing cookie secret
  k8s_info:
    api_version: v1
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ ansible_operator_meta.name }}-session-secret'
  register: session_secret

- name: Create cookie secret
  no_log: true
  k8s:
    definition:
      api_version: v1
      kind: Secret
      metadata:
        name: '{{ ansible_operator_meta.name }}-session-secret'
        namespace: '{{ ansible_operator_meta.namespace }}'
      stringData:
        session_secret: "{{ lookup('password', '/dev/null') }}"
  when: session_secret.resources|length == 0
