# TODO: check for availability of elasticsearches.elasticsearch.k8s.elastic.co to
#       determine if we can create ElasticSearch and related certificates. Can't
#       directly look up the CustomResourceDefinition because it requires ClusterRole scope.

- name: Setup Certificates for ElasticSearch
  include_tasks: component_certificates.yml

- name: Setup ElasticSearch
  include_tasks: component_elasticsearch.yml

- name: Create Smart Gateway instance
  include_tasks: component_events_smartgateway.yml
