---
- name: Run ansible-lint
  hosts: all
  tasks:
    - name: install virtualenv
      ansible.builtin.pip:
        name: virtualenv
        state: latest
        extra_args: "--user"

    - name: Install ansible-lint
      ansible.builtin.pip:
        name:
          - ansible-core
          - ansible-lint
        state: latest
          #virtualenv: "{{ ansible_env.HOME }}/{{ zuul.project.src_dir }}/.venv"

    - name: Run ansible-lint
      ansible.builtin.shell:
        cmd: |
          python -m ansiblelint -c .ansible-lint {{ item }}
        chdir: "{{ ansible_env.HOME }}/{{ zuul.project.src_dir }}"
          #environment:
          #  PATH: "{{ ansible_env.HOME }}/{{ zuul.project.src_dir }}/.venv/bin/"
      with_items:
        - "build"
        - "ci"
