---
- hosts: controller
  tasks:
    - name: "Log into the cluster"
      ansible.builtin.import_role:
        name: rhol_crc
        tasks_from: add_crc_creds.yml

    - name: "Get the oc version info"
      ansible.builtin.shell:
        cmd: |
          oc version | grep Server | cut -d' ' -f3
      register: oc_version

    - name: "Fail if the version is not the expected one"
      when: oc_version.stdout != ocp_version
      fail:
        msg: "The ocp version ({{ oc_version.std_out }}) is not the expected one ({{ ocp_version }})"
