---
- hosts: all
  tasks:
    - name: Return zuul data
      zuul_return:
        data:
          zuul:
            pause: true
          # What do I need?
          test: "{{ test_input }}"
          provider_ip_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address']  }}"
