---
- hosts: controller
  name: "Wait for 4.14 to work"
  tasks:
    - name: Get crc logs
      ansible.builtin.shell:
        cmd: |
          cat ~/crc-start.log
      register: cat

    - name: "Show crc start logs"
      ansible.builtin.debug:
        var: cat.stdout

    - name: "Get crc info"
      ansible.builtin.shell:
        cmd: |
          crc version

    - name: "Run crc status"
      ansible.builtin.shell:
        cmd: |
          crc status

    - name: "Get the cache dir for crc"
      ansible.builtin.shell:
        cmd: |
          crc status | grep "Cache Directory" | cut -d' ' -f3
      register: cache_dir

    - name: Get crc status in json format
      ansible.builtin.shell:
        cmd: |
          crc status -o json

    - name: "Show the contents of of cache dir"
      ansible.builtin.shell:
        cmd: |
          ls {{ cache_dir.stdout }} | grep {{ crc_ocp_bundle | basename }}
          ls {{ cache_dir.stdout }}/{{ crc_ocp_bundle | basename | splitext | first }}/

    - name: "Set the name for kubeconfig"
      ansible.builtin.set_fact:
        kubeconfig: "{{ cache_dir.stdout }}/{{ crc_ocp_bundle | basename | splitext | first }}/kubeconfig"

    - name: Get oc status from crc
      ansible.builtin.shell:
        cmd:
          crc status -o json

    - name: "Get oc status"
      ansible.builtin.shell:
        cmd: |
          KUBECONFIG={{ kubeconfig }} oc status
      register: output
      ignore_errors: true
      retries: 100
      delay: 6
      until: output.rc == 0

    - name: Get oc status from crc
      ansible.builtin.shell:
        cmd:
          crc status -o json
      register: crc_status

    - ansible.builtin.debug:
        var: crc_status | from_json

    - ansible.builtin.set_fact:
        crc_status_json: "{{ crc_status | from_json }}"

    - name: "Link the KUBECONFIG file to ~/.kube/config"
      ansible.builtin.shell:
        cmd: |
          unlink ~/.kube/config || true
          ln -s {{ kubeconfig }} ~/.kube/config
      ignore_errors: true

    - name: "Get oc status"
      ansible.builtin.shell:
        cmd: |
          oc status
