---
# Based on https://raw.githubusercontent.com/openstack-k8s-operators/nova-operator/bc10c4f579f8538899ac7bc5f87bfdb62d7042a4/ci/nova-operator-base/playbooks/collect-logs.yaml
- hosts: all
  name: Create zuul-output log dir
  gather_facts: false
  tasks:
    - name: Create log dir
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/zuul-output/logs"
        state: directory
        mode: "0755"

- hosts: controller
  name: Collect logs on the controller
  gather_facts: false
  tasks:
    - name: "Setup play vars"
      ansible.builtin.include_tasks: "common-tasks.yml"

    - name: "Create log dir"
      ansible.builtin.file:
        path: "{{ logfile_dir }}"
        state: directory
        mode: "0755"

    - name: "Log into the cluster"
      ansible.builtin.import_role:
        name: rhol_crc
        tasks_from: add_crc_creds.yml

    - name: "Gather logs from stf deployment"
      ansible.builtin.import_role:
        name: '../build/stf-collect-logs'

    - name: "Copy generated logs"
      ansible.builtin.shell: |
        cp {{ ansible_env.HOME }}/*.log .
      args:
        chdir: "{{ logfile_dir }}"
      changed_when: true
      ignore_errors: true

- hosts: all
  name: Copy files from controller on node
  gather_facts: false
  tasks:
    - name: Copy files from controller on node
      ansible.builtin.include_role:
        name: fetch-output
