---
# This file will be copied to the controller, and then run from there using shell: cmd=`ansible-playbook ...`
# This is required because I want to use some role from the ci-framework, and the implementation includes some plugins/actions which aren't installed properly. It's because zuul doesn't support installing from collections, and the actions won't exist on the zuul executer.
- hosts: localhost
  gather_facts: true
  environment:
    ANSIBLE_ROLES_PATH: "{{ ansible_env.HOME }}/{{ zuul.projects['github.com/openstack-k8s-operators/ci-framework'].src_dir }}/ci_framework/roles{{ (':' + ansible_env.ANSIBLE_ROLES_PATH ) if ansible_env.ANSIBLE_ROLES_PATH is defined }}"
    ANSIBLE_ACTION_PLUGINS: "{{ ansible_env.HOME}}/{{ zuul.projects['github.com/openstack-k8s-operators/ci-framework'].src_dir }}/ci_framework/plugins/action{{ (':' + ansible_env.ANSIBLE_ACTION_PLUGINS ) if ansible_env.ANSIBLE_ACTION_PLUGINS is defined }}"
  tasks:
    - name: "Log into OpenShift"
      ansible.builtin.shell:
        cmd: |
          oc login -u {{ cifmw_openshift_user }} -p {{ cifmw_openshift_password }} --insecure-skip-tls-verify=true {{ cifmw_openshift_api }}
      retries: 10
      delay: 10

    - name: "Log into OpenShift"
      ansible.builtin.shell:
        cmd: |
          oc login -u {{ cifmw_openshift_user }} -p {{ cifmw_openshift_password }} --insecure-skip-tls-verify=true {{ cifmw_openshift_api }}

    # I need to figure out why the ci_script module is not available in the environment, since the command above is taking the login command out of that.
    #- name: "Login into openshift"
    #  ansible.builtin.include_role:
    #    name: "{{ zuul.projects['github.com/openstack-k8s-operators/ci-framework'].src_dir }}/ci_framework/roles/openshift_login"
    #  vars:
    #    cifmw_openshift_login_kubeconfig: "{{ cifmw_openshift_kubeconfig }}"
    #    cifmw_openshift_login_user: "{{ cifmw_openshift_user }}"
    #    cifmw_openshift_login_password: "{{ cifmw_openshift_password }}"
    #    # from: https://github.com/openstack-k8s-operators/ci-framework/blob/1cc9e123a74a081a4a9335f4277fe1649cb04e40/docs/source/usage/01_usage.md?plain=1#L17
    #    # TODO: Update this so I don't have to set it. This shouldn't be set on the controller, should it?
    #    cifmw_path: "~/.crc/bin:~/.crc/bin/oc:~/bin:{{ ansible_env.PATH }}"

