---
- name: "Do pre-work to get kubeconfig"
  hosts: controller
  vars:
    ci_framework_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/openstack-k8s-operators/ci-framework'].src_dir }}"
  environment:
    PATH: "~/.crc/bin:~/.crc/bin/oc:~/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: "Set the sto_dir if it isn't already set"
      ansible.builtin.set_fact:
        sto_dir: '{{ ansible_env.HOME }}/{{ zuul.projects["github.com/infrawatch/service-telemetry-operator"].src_dir }}'
      when: sto_dir | default('') | length == 0

    - name: "Load zuul parameters"
      ansible.builtin.include_vars:
        file: "{{ ansible_user_dir }}/ci-framework-data/artifacts/parameters/zuul-params.yml"

    - name: "Run bootstrap tasks"
      ansible.builtin.include_tasks: "{{ ci_framework_dir }}/roles/cifmw_setup/tasks/bootstrap.yml"

    - name: "Run ci_framework infra tasks"
      ansible.builtin.include_tasks: "{{ ci_framework_dir }}/roles/cifmw_setup/tasks/infra.yml"
      vars:
        cifmw_use_opn: false
        cifmw_use_devscripts: false
        cifmw_basedir: "{{ ansible_user_dir }}/ci-framework-data/"
        cifmw_openshift_setup_skip_internal_registry_tls_verify: true

    - name: Run make targets for setup
      community.general.make:
        chdir: '{{ ansible_env.HOME }}/{{ zuul.projects["github.com/openstack-k8s-operators/ci-framework"].src_dir }}'
        target: "{{ item }}"
      with_items:
        - setup_tests
        - setup_molecule

