---
# This file will be copied to the controller, and then run from there using shell: cmd=`ansible-playbook ...`
# This is required because I want to use some role from the ci-framework, and the implementation includes some plugins/actions which aren't installed properly. It's because zuul doesn't support installing from collections, and the actions won't exist on the zuul executer.
- hosts: localhost
  gather_facts: true
  tasks:
    - name: "Log into OpenShift"
      ansible.builtin.shell:
        cmd: |
          oc login -u {{ cifmw_openshift_user }} -p {{ cifmw_openshift_password }} --insecure-skip-tls-verify=true {{ cifmw_openshift_api }}
      retries: 10
      delay: 10

    - name: "Link the kubeconfig file"
      ansible.builtin.shell:
        cmd: |
          mkdir -p {{ cifmw_openshift_kubeconfig | dirname }}
          ln -s {{ ansible_env.HOME }}/.kube/config {{ cifmw_openshift_kubeconfig }}
