---
- name: "Do pre-work to get kubeconfig"
  hosts: controller
  vars:
    ci_framework_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/openstack-k8s-operators/ci-framework'].src_dir }}"
  environment:
    PATH: "~/.crc/bin:~/.crc/bin/oc:~/bin:{{ ansible_env.PATH }}"
  tasks:
      # this task is temperory, eventually, this whole play will be in a separate file, which will do the common tasks already.
    - name: "Set the sto_dir if it isn't already set"
      ansible.builtin.set_fact:
        sto_dir: '{{ ansible_env.HOME }}/{{ zuul.projects["github.com/infrawatch/service-telemetry-operator"].src_dir }}'
      when: sto_dir | default('') | length == 0

    - name: "Run bootstrap playbook"
      ansible.builtin.shell:
        cmd: |
          ansible-playbook -e@{{ ansible_user_dir }}/ci-framework-data/artifacts/parameters/zuul-params.yml {{ ci_framework_dir }}/playbooks/01-bootstrap.yml
        chdir: "{{ ci_framework_dir }}"

    - name: Run make targets for setup
      community.general.make:
        chdir: '{{ ansible_env.HOME }}/{{ zuul.projects["github.com/openstack-k8s-operators/ci-framework"].src_dir }}'
        target: "{{ item }}"
      with_items:
        - setup_tests
        - setup_molecule

    - name: "Copy the login playbook to the controller"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/pre-get_kubeconfig.yml"
        dest: "{{ ansible_user_dir }}/login.yml"

    - name: "Run the login playbook"
      ansible.builtin.shell:
        cmd: |
         ansible-playbook -e@{{ ansible_user_dir }}/ci-framework-data/artifacts/parameters/zuul-params.yml {{ ansible_user_dir }}/login.yml
