---
- name: "Prepare the environment for running stf"
  hosts: controller
  tasks:
    - name: "Setup play vars"
      ansible.builtin.include_tasks: "common-tasks.yml"

    - name: "Update pip"
      ansible.builtin.pip:
        name: pip
        state: latest
        extra_args: "-U"

    - name: "Install pre-reqs from pip"
      ansible.builtin.pip:
        requirements: "{{ sto_dir }}/build/stf-run-ci/requirements.txt"
        chdir: "{{ sto_dir }}"
        state: present

    - name: "Install ansible collections"
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ item }}"
      with_items:
        - "kubernetes.core:2.3.2"
        - "community.general"

    - name: "Log into the cluster"
      ansible.builtin.import_role:
        name: rhol_crc
        tasks_from: add_crc_creds.yml

    - name: "Create the service-telemetry project"
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        state: present
      retries: 3
      delay: 30
