---
- name: "Prepare the environment for running stf"
  hosts: controller
  tasks:
    # NOTE: maybe this prepare isn't required in the CRC provider, since it is for STF...
    # I can probably split this up into two playbooks, prepare and prepare STF.
    # Prepare will run these tasks, common-tasks needs to remove the scenario-specific vars file, and it should be explicitly be included in the STF play
    - name: "Setup play vars"
      ansible.builtin.include_tasks: "common-tasks.yml"

    - name: "Install Python 3.12"
      ansible.builtin.package:
        name:
          - python3.12
          - python3.12-pip 
        state: latest
      become: true

    - name: "Update pip"
      ansible.builtin.pip:
        name: pip
        state: latest
        extra_args: "-U"
        executable: pip3.12

    - name: "Install pre-reqs from pip"
      ansible.builtin.pip:
        requirements: "{{ sto_dir }}/build/stf-run-ci/requirements.txt"
        chdir: "{{ sto_dir }}"
        state: present
        executable: pip3.12

    - name: "Install ansible collections"
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ item }}"
      with_items:
        - "kubernetes.core:5.0.0"
        - "community.general"

        # this won't succeed, since it needs kubeconfif to be set
        # Try using openshift_login instead, since the vars are already set from the provider job.
    #- name: "Log into the cluster"
    #  ansible.builtin.import_role:
    #    name: rhol_crc
    #    tasks_from: add_crc_creds.yml

    - name: "Show the openshift cluster information from the provider"
      ansible.builtin.debug:
        msg: |
          The provider_openshift_login_api value is {{ provider_openshift_login_api | default('unset')}}.
          The provider_openshift_login_user is {{ provider_openshift_login_user | default('unset') }}
          The provider_openshift_login_password is {{ provider_openshift_login_password | default('unset')}}

    # The vars are hardcoded for now, but will become vars later.
    - name: "Log into the cluster"
      ansible.builtin.import_role:
        name: openshift_login
      vars:
        cifmw_openshift_login_api: "https://api.crc.testing:6443"
        cifmw_openshift_login_user: "kubeadmin"
        cifmw_openshift_login_password: "12345678"

        # After this point is specifically STF, which can be removed for now.
        # This won't let STF pass, but it will be fine.
#    - name: "Create the service-telemetry project"
#      kubernetes.core.k8s:
#        api_version: v1
#        kind: Namespace
#        name: "{{ namespace }}"
#        state: present
#      retries: 3
#      delay: 30
