---
- name: "Do pre-work to get kubeconfig"
  hosts: controller
  vars:
    ci_framework_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/openstack-k8s-operators/ci-framework'].src_dir }}"
  environment:
    PATH: "~/.crc/bin:~/.crc/bin/oc:~/bin:{{ ansible_env.PATH }}"
  tasks:
      # this task is temperory, eventually, this whole play will be in a separate file, which will do the common tasks already.
    - name: "Set the sto_dir if it isn't already set"
      ansible.builtin.set_fact:
        sto_dir: '{{ ansible_env.HOME }}/{{ zuul.projects["github.com/infrawatch/service-telemetry-operator"].src_dir }}'
      when: sto_dir | default('') | length == 0

    - name: Run make targets for setup
      community.general.make:
        chdir: '{{ ansible_env.HOME }}/{{ zuul.projects["github.com/openstack-k8s-operators/ci-framework"].src_dir }}'
        target: "{{ item }}"
      with_items:
        - setup_tests
        - setup_molecule

    - name: "Run bootstrap playbook"
      ansible.builtin.shell:
        cmd: |
          ansible-playbook -e@{{ ansible_user_dir }}/ci-framework-data/artifacts/parameters/zuul-params.yml {{ ci_framework_dir }}/ci_framework/playbooks/01-bootstrap.yml
        chdir: "{{ ci_framework_dir }}"

    - name: "Check for oc"
      ansible.builtin.shell:
        which oc
      ignore_errors: true

      ## check for oc in the .crc dir
      #
    # need -e zuul-parameters-file
    # in $HOME/zuul-output-logs/ ## should be my logfile dir in jobs
    - ansible.builtin.copy:
        src: "{{ playbook_dir }}/pre-get_kubeconfig.yml"
        dest: "{{ ansible_user_dir }}/login.yml"

    - name: "Run the login role"
      ansible.builtin.shell:
        cmd: |
         ansible-playbook -e@{{ ansible_user_dir }}/ci-framework-data/artifacts/parameters/zuul-params.yml {{ ansible_user_dir }}/login.yml

    - name: "Update teh kubeconfig path"
      set_fact:
        cifmw_openshift_kubeconfig: "/home/zuul/.kube/config"
    - name: Check for the kubeconfig file
      ansible.builtin.shell:
        cmd: |
          ls {{ cifmw_openshift_kubeconfig }}

- name: "Prepare the environment for running stf"
  hosts: controller
  tasks:
    - name: "Set the sto_dir if it isn't already set"
      ansible.builtin.set_fact:
        sto_dir: '{{ ansible_env.HOME }}/{{ zuul.projects["github.com/infrawatch/service-telemetry-operator"].src_dir }}'
      when: sto_dir | default('') | length == 0

    - name: "Get vars common to all jobs"
      ansible.builtin.include_vars:
        file: "vars-zuul-common.yml"

    - name: "Get scenario-specific vars"
      ansible.builtin.include_vars:
        file: "vars-{{ scenario }}.yml"

    - name: "Update pip"
      ansible.builtin.pip:
        name: pip
        state: latest
        extra_args: "-U"

    - name: "Install pre-reqs from pip"
      ansible.builtin.pip:
        requirements: "{{ sto_dir }}/build/stf-run-ci/requirements.txt"
        chdir: "{{ sto_dir }}"
        state: present

    - name: "Install ansible collections"
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ item }}"
      with_items:
        - "kubernetes.core:2.3.2"
        - "community.general"

    - name: "Log into the cluster"
      ansible.builtin.import_role:
        name: rhol_crc
        tasks_from: add_crc_creds.yml
      vars:
        cifmw_rhol_crc_kubeconfig: "{{ ansible_env.HOME }}/.kube/config"

    - name: "Create the service-telemetry project"
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        state: present
      retries: 3
      delay: 30
