---
- name: "Prepare the environment for running stf"
  hosts: controller
  tasks:
    - name: "Update pip"
      ansible.builtin.pip:
        name: pip
        state: latest
        extra_args: "-U"

    - name: "Check for the requirements file"
      ansible.builtin.shell:
        ls {{ playbook_dir }}/../build/stf-run-ci
      register: contents
      ignore_errors: true

    - name: "Show the contents of the dir"
      ansible.builtin.debug:
        var: contents

    - name: "Install pre-reqs from pip"
      ansible.builtin.pip:
        requirements: "../build/stf-run-ci/requirements.txt"
        chdir: "{{ playbook_dir }}"
        state: present

    - name: "Install ansible collections"
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ item }}"
      with_items:
        - "kubernetes.core:2.3.2"
        - "community.general:6.2.0"

    - name: "Log into the cluster"
      ansible.builtin.import_role:
        name: rhol_crc
        tasks_from: add_crc_creds.yml

    - name: "Create the service-telemetry project"
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "service-telemetry"
        state: present
      retries: 3
      delay: 30
