---
- name: "Run tests to verify that STF runs as expected"
  hosts: controller
  tasks:
    - name: "Setup play vars"
      ansible.builtin.include_tasks: "common-tasks.yml"

    - name: "Log into the cluster"
      ansible.builtin.import_role:
        name: rhol_crc
        tasks_from: add_crc_creds.yml

    - name: "Run STF smoketests"
      ansible.builtin.shell:
        cmd: |
          OCP_PROJECT={{ namespace }} CLEANUP=false ./tests/smoketest/smoketest.sh > {{ logfile_dir }}/smoketest.log 2>&1
        chdir: "{{ sto_dir }}"
      changed_when: false
